version: '2'
services:
  b4kjhralab-app:
    image: b4kjhralab
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://b4kjhralab-mssql:1433;database=b4kjhralab
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  b4kjhralab-mssql:
    extends:
      file: mssql.yml
      service: b4kjhralab-mssql
